trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  workingDirectory: './LibraryApi'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  workingDirectory: ${{ variables.workingDirectory }}
  inputs:
    command: 'restore'
    projects: ${{ variables.solution }}
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build Solution
  workingDirectory: ${{ variables.workingDirectory }}
  inputs:
    command: 'build'
    projects: ${{ variables.solution }}
