version: '3'
services:
  library-api:
    build: .
    environment:
      ConnectionStrings__LibraryDatabase: ${LIBRARYDB_CONNECTIONSTRING}
    ports:
      - 8000:80
    networks:
      - library-network
    depends_on:
      - library-db
  
  library-db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - library-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  library-network:
    name: library-network